### ISSUE TITLE
Audit checklist (v0)

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-contracts#90]
* [x] [VestingToken.sol](https://github.com/radicle-dev/radicle-contracts/blob/df01a093d8055b0df4cf146192a8bbd7f3066408/contracts/Governance/VestingToken.sol) (df01a093d8055b0df4cf146192a8bbd7f3066408)
  * Based on the melonport vesting contract
  * Update for solidity 0.7.5
  * Added cliff period and removed unused/redundant functionality
* [x] [RadicleToken.sol](https://github.com/radicle-dev/radicle-contracts/blob/7a1d8d8be2e0d838fe2d3aae117f821abaf1551f/contracts/Governance/RadicleToken.sol) (7a1d8d8be2e0d838fe2d3aae117f821abaf1551f)
  * Based on the Compound COMP token with adjusted totalSupply
  * Added `burnFrom` method and made fully EIP20 compatible
  * Updated for solidity 0.7.5
* [x] [~~Treasury.sol~~](https://github.com/radicle-dev/radicle-contracts/blob/a47f0c7d747152558070bc8048d7560423af2c61/contracts/Governance/Treasury.sol) (a47f0c7d747152558070bc8048d7560423af2c61)
* [x] [Governor.sol](https://github.com/radicle-dev/radicle-contracts/blob/d09ae0df96ecd846f95452cd492867092cf91c29/contracts/Governance/Governor.sol) (d09ae0df96ecd846f95452cd492867092cf91c29)
  * Based on the Compound Governor Alpha contract
  * A few modifications to make solidity 0.7.5 compatible
  * Updated voting thresholds
* [x] [Timelock.sol](https://github.com/radicle-dev/radicle-contracts/blob/5d11d22833afccd3472ba2cc3f8e04abda5a10a7/contracts/Governance/Timelock.sol) (5d11d22833afccd3472ba2cc3f8e04abda5a10a7)
  * Based on the Compound Timelock contract
  * Updated to make solidity 0.7.5 compatible

---

* [x] [Registrar.sol](https://github.com/radicle-dev/radicle-contracts/blob/eb43a390f853947146166e613c7a4282aae39d80/contracts/Registrar.sol) (eb43a390f853947146166e613c7a4282aae39d80)
  * Loosely based on the EthRegistrar contracts from ENS.
